name: Commit Latest Top Five from Chadsoft API

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_recent_runs:
    name: Update recentRuns.json
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Generate recentRuns.json
      run: node fetch-chadsoft.js

    - name: Stash recentRuns.json
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add recentRuns.json
        git stash

    - name: Checkout gh-pages
      uses: actions/checkout@v3
      with:
        ref: gh-pages
      
    - name: Commit recentRuns.json to gh-pages
      run: |
        git stash apply || true
        git checkout --theirs recentRuns.json
        git add recentRuns.json
        git commit -m "Update recentRuns.json - $(date '+%Y-%m-%d %H:%M')"
        git push origin HEAD:gh-pages

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}