name: Deploy Website to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy_website:
    name: Deploy Website
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: website